-- MySQL Script generated by MySQL Workbench
-- Tue Mar  8 22:10:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pcstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pcstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pcstore` DEFAULT CHARACTER SET utf8 ;
USE `pcstore` ;

-- -----------------------------------------------------
-- Table `pcstore`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcstore`.`cliente` (
  `id_cliente` CHAR(5) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `clientecol` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcstore`.`cab_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcstore`.`cab_venta` (
  `num_boleta` CHAR(5) NOT NULL,
  `num_factura` CHAR(8) NULL,
  `id_cliente` CHAR(5) NOT NULL,
  `total_bol` DECIMAL(8,2) NULL,
  PRIMARY KEY (`num_boleta`),
  INDEX `fk_factura_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pcstore`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcstore`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcstore`.`categoria` (
  `id_categoria` CHAR(5) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcstore`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcstore`.`producto` (
  `id_producto` CHAR(5) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(7,2) NULL,
  `stock` VARCHAR(45) NULL,
  `id_categoria` INT NOT NULL,
  `garantia` INT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `pcstore`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcstore`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcstore`.`detalle_venta` (
  `cantidad` INT NULL,
  `precio` DECIMAL(8,2) NULL,
  `factura_num_factura` INT NOT NULL,
  `producto_id_producto` CHAR(5) NOT NULL,
  INDEX `fk_detalle_factura_factura1_idx` (`factura_num_factura` ASC) VISIBLE,
  INDEX `fk_detalle_venta_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_factura_factura1`
    FOREIGN KEY (`factura_num_factura`)
    REFERENCES `pcstore`.`cab_venta` (`num_boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `pcstore`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcstore`.`Garantia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcstore`.`Garantia` (
  `id_garantia` CHAR(5) NOT NULL,
  `observacion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `producto_id_producto` INT NOT NULL,
  `Vigencia` INT NULL,
  PRIMARY KEY (`id_garantia`),
  INDEX `fk_Reclamos_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_Reclamos_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `pcstore`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
